### PR TITLE
raft: remove direct access to RaftLog.entries

### PR DESCRIPTION
**Pull request by NingLin-P**
Signed-off-by: linning <linningde25@gmail.com>

### CODE REVIEW

**Comment by yujqiao** [comment]
I think this PR really improves tests and makes life easier. Sadly it has been staled for a long time and there's no sign for this getting merged.

**Comment by NingLin-P** [comment]
PTAL again @Connor1996

**Comment by Connor1996** [comment]
I notice that it removes the code of 2C, does it change the implementation of 2C?

**Comment by NingLin-P** [comment]
> I notice that it removes the code of 2C, does it change the implementation of 2C?

Yes, it did change a little bit of the implementation of 2C. Previous, with direct access to `RaftLog.entries`, the tests assume `RaftLog.entries` contains all log entries (stabled and unstable), so we need to implement `RaftLog.maybeCompact` to compact `RaftLog.entries` in case it grow unlimited. But with `RaftLog.allEntries` people can chose to store stabled entries to `Storage` and `RaftLog.maybeCompact` is no more necessary.

**Comment by Connor1996** [comment]
I'm afraid it affects the ongoing implementation of this round of talent plan students. Let's merge it later. 
And does the doc need to update?

**Comment by NingLin-P** [comment]
> I'm afraid it affects the ongoing implementation of this round of talent plan students. Let's merge it later.
> And does the doc need to update?

Ok, I think the doc does not need to change.

**Pull request closed without merging**
