### PR TITLE
Fix TestCommitConflictRollback4B

### PR DESCRIPTION
**Pull request by OneSizeFitsQuorum**
According to the [vldb-2021-labs's](https://github.com/vldbss-2021/vldb-2021-labs/blob/master/tinykv/kv/transaction/commands4b_test.go#L526) code, commit a rollback transaction should report an error, which is more intuitive in my opinion.

### CODE REVIEW

**Comment by OneSizeFitsQuorum** [comment]
@Connor1996 cc

**Review by Connor1996 — COMMENTED** [review]
Reasonable. Please check if the related doc should be updated.

**Comment by Connor1996** [comment]
BTW, @you06 If there is any change that can be picked to TinyKV from vldb-2021-lab

**Comment by you06** [comment]
@Connor1996 Yes, there are some, I'll submit those patches in other PRs.

**Review by you06 — APPROVED** [review]

**Comment by OneSizeFitsQuorum** [comment]
> Reasonable. Please check if the related doc should be updated.

Personally, I feel that lab4 documents are not very complete, and many corner cases can only be found through testing. I have checked all the documents. Since these corner cases have not been described, I have not found any documents that need to be updated

**Review by Connor1996 — APPROVED** [review]

**Pull request merged**
