### PR TITLE
fix #171 let newRaft take care of peers and Prs

### LINKED ISSUE #171: TestLeaderElectionOverwriteNewerLogs2AB forget to setup peers information?
https://github.com/pingcap-incubator/tinykv/blob/edb12af93f17321030036ffcfcc7723239c3f8ad/raft/raft_test.go#L121
should be something like
`
cfg := func(c *Config) {
		c.peers = idsBySize(5)
	}
`

### PR DESCRIPTION
**Pull request by schneiderlin**
fix #171

### CODE REVIEW

**Comment by NingLin-P** [comment]
Thanks! there are many `var cfg func(*Config)` defined, could you also fix them?

**Comment by schneiderlin** [comment]
you mean replace it with `nil`?

**Comment by NingLin-P** [comment]
> you mean replace it with `nil`?

No, I mean there are many `var cfg func(*Config)` , we should change them to `cfg := func(c *Config) { c.peers = idsBySize(5) }` too.

**Comment by schneiderlin** [comment]
sorry, I don't get it. when the parameter of `newNetworkWithConfig` is either `nil` or `nopStepper` as in all other places, it doesn't need an extra function to set `c.peers`.

in `nil` case: `newTestConfig` contains peerAddrs.
in `nopStepper` case: peers don't matter at all.

**Comment by NingLin-P** [comment]
You are right, sorry for the overlook!

**Review by NingLin-P — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
